### ISSUE TITLE
Show GUI editor 

### ISSUE THREAD

**Issue by nikreiman** [teragonaudio/MrsWatson#160]
Useful during plugin development

**Comment by ZECTBynmo** [comment]
+1!

**Comment by nikreiman** [comment]
Experimentally introduced in 754dd8a. If you want to try out the feature, it is available with the `--editor` switch, which is currently hidden in `--help`. There are known issues on Mac OS X (namely, the window title not showing up on 10.10 and a crash on shutdown), and Windows is unimplemented. The Linux code should work, but I haven't tested it yet and it is based on a very old branch.
