### ISSUE TITLE
4/4 time in MidiSourceFile.c

### ISSUE THREAD

**Issue by pepperpepperpepper** [teragonaudio/MrsWatson#196]
midi/MidiSourceFile.c, line 214 you've written:
   // TODO: If the time signature is not 4/4, this calculation will be wrong
Not sure how that can be, since division in the midi header is relative to the quarter note...and the quarter note is the basic subdivision of all standard/readable musical time signatures. Is this really an issue? 
Shouldn't it be fine for 2/2, 3/4, 4/4, 5/4, 6/8, 7/4, 9/8, 9/4, 11/4, 13/4...etc time signatures?

**Comment by nikreiman** [comment]
Hmm, I think you're right. That TODO is pretty old (from around this time last year), so I don't think it's valid anymore.

**Comment by pepperpepperpepper** [comment]
awesome!
