### ISSUE TITLE
Realtime audio input

### ISSUE THREAD

**Issue by gamecompiler** [teragonaudio/MrsWatson#212]
Hi, is it possible to give MrsWatson my soundCard as realtime input ?
I would like to use StereoMix with the BeatCounter plugin.

Thanks in Advance.

**Comment by nikreiman** [comment]
@gamecompiler Sorry, this feature is currently not supported in MrsWatson. MrsWatson does have a `--realtime` command line switch, where it will process audio online. However it does not have the ability to read directly from the soundcard.
