### ISSUE TITLE
Nexus generating notes out of pitch

### ISSUE THREAD

**Issue by evandelacruz** [teragonaudio/MrsWatson#245]
First of all, **thank you** so much for creating this amazing program.

**Scenario**:
Using a midi file, MrsWatson, and ReFx Nexus, generate an audio file

**Problem**: 
The resulting audio seems to have some notes that are not the pitch specified in the midi file.  The majority of notes are correct, these detuned notes make up maybe 10% of all the notes.  I have tried with very simple files, such as the one attached, with no luck.

**Notable** (I think):
The out of tune notes are detuned by less than a half-step.  So I do not think that MrsWatson is sending the wrong note value.  It is more like some controller data is bending certain notes a few cents here or there, or some other non-midi related tuning/pitch feature such as portamento that is getting stuck.  
My instinct was initially that the problem is with Nexus, not MrsWatson.
However, if I send the same midi file to MrsWatson from a midi player, it plays perfectly as expected.  That is being played in real-time though, so maybe that makes a difference?
One other note is that I have only noticed this with longer sustaining sounds (which my program is also sending longer note lengths for).
I am sending the same velocity (80) for every note.

**Environment**: 
Windows 10 64 Bit Intel i7
MrsWatson64.exe 0.9.8 build 20150122
ReFx Nexus 2.7.3 64bit

**Expected/actual results of attached test files**:
At least first eight notes are all supposed to be B-flat.  However, the 6th and 7th note in the sequence are coming out a tad sharper than they are supposed to be.  Not quite a B... somewhere between B-flat and B.

**Steps to reproduce**:
Using the attached midi file, run:
`mrswatson64.exe -q --verbose --log-file c:\xampp\tmp\mrswatson_log-pitch.txt --tempo 135.12 --midi-file "TestNexus.mid" --output "TestNexus.raw" --plugin "C:\\Program Files (x86)\\reFX\\Nexus\\Nexus.dll,C:\\Program Files (x86)\\reFX\\Nexus\\Nexus BA Mass Effect 2.fxp"`

If it is a bug in MrsWatson, I am happy to try fixing it and submitting a patch.  But for now I don't really know where to look.  I will try poking around.

I'm attaching the midi file and the MrsWatson log.  I tried to attach the raw audio file but it was too big.  Let me know if you need it and I will upload it somewhere. (Update: I also attached the fxp file for nexus.  Its a factory preset.)

[TestNexus.zip](https://github.com/teragonaudio/MrsWatson/files/357372/TestNexus.zip)
[mrswatson_log-pitch-nexus.zip](https://github.com/teragonaudio/MrsWatson/files/357414/mrswatson_log-pitch-nexus.zip)
[Nexus BA Mass Effect 2.zip](https://github.com/teragonaudio/MrsWatson/files/357445/Nexus.BA.Mass.Effect.2.zip)

**Comment by evandelacruz** [comment]
I suppose it's also worth explicitly mentioning that I do not have this problem with other vsti's.  Only nexus.

**Comment by evandelacruz** [comment]
I went ahead and did a build from the master branch to see if this problem still exists in the latest version.  I didn't see anything in the change logs talking about this, but I hoped I might just get lucky.  I will report back with test results.  Just using my ear, I think so far everything looks good.

**Comment by evandelacruz** [comment]
Building from master, I am not able to reproduce this issue.  I'm going to run a few more tests tonight and if I cannot reproduce the issue still I will close this.

**Comment by nikreiman** [comment]
Thanks for the very detailed bug report! Is it safe to close this issue now?

**Comment by evandelacruz** [comment]
Yes all seems good.  Thanks for Mrs Watson.
