### ISSUE TITLE
Absolute plugin paths no longer work on Windows

### ISSUE THREAD

**Issue by evandelacruz** [teragonaudio/MrsWatson#246]
Using absolute paths used to work with --plugin.   It no longer does (on windows).
If I use "c:\blah\blah\plugin", MrsWatson thinks the plugin I am looking for is called "c".

I believe this is due to [this fix](https://github.com/teragonaudio/MrsWatson/commit/2ec36839ba53b111580336a7e9aa51fd932cd600) which made the colon have a special meaning for shell plugins.

There is a simple workaround, so you might just decide to close this issue. 
The workaround is to use --plugin-root to specify the folder and then only use the plugin name, instead of the full path, for --plugin.

**Comment by nikreiman** [comment]
Good catch, this should be an easy fix.
