### ISSUE TITLE
Tempo changes after the first tempo event are seemingly ignored

### ISSUE THREAD

**Issue by hillct** [teragonaudio/MrsWatson#272]
It appears that the MrsWatson ignores tempo change events other than the first one encountered. While output seems to indicate it encounters the change events, it always set the same tempo upon hitting each event. Sample files are/will be attached, related to the below output:

`
./mrswatson64 --midi-file ../../Little\ File.mid --output ./out.wav --plugin ../../DSK-TheGrand/DSK-TheGrand.vst
- 00000000 000001 MrsWatson version 0.9.8 initialized, build 20150122
- 00000000 000001 Plugin '../../DSK-TheGrand/DSK-TheGrand.vst' is of type VST2.x
- 00000000 000001 Opening VST2.x plugin '../../DSK-TheGrand/DSK-TheGrand.vst'
- 00000000 001490 Number of channels = 32. Will only arrange 8 speakers.
W 00000000 001490 Ignoring MIDI meta event of type 0x20 at 0
W 00000000 001490 Ignoring MIDI meta event of type 0x20 at 0
- 00000000 001491 Starting processing input source
- 00000000 001491 Setting tempo to 81
- 00176128 001616 Setting tempo to 81
- 00209408 001641 Setting tempo to 81
- 00210432 001642 Setting tempo to 81
- 00211968 001644 Setting tempo to 81
- 00213504 001646 Setting tempo to 81
- 00214528 001647 Setting tempo to 81
- 00216064 001648 Setting tempo to 81
- 00217600 001649 Setting tempo to 81
- 00218624 001651 Setting tempo to 81
- 00352768 001825 Setting tempo to 81
- 00357376 001829 Setting tempo to 81
- 00361984 001833 Setting tempo to 81
- 00367104 001840 Setting tempo to 81
- 00371712 001844 Setting tempo to 81
- 00376832 001849 Setting tempo to 81
- 00381440 001854 Setting tempo to 81
- 00386048 001858 Setting tempo to 81
- 00391168 001864 Setting tempo to 81
- 00395776 001868 Setting tempo to 81
- 00400896 001873 Setting tempo to 81
- 00405504 001879 Setting tempo to 81
- 00410624 001890 Setting tempo to 81
- 00415232 001908 Setting tempo to 81
- 00419840 001911 Setting tempo to 81
- 00424960 001917 Setting tempo to 81
- 00429568 001920 Setting tempo to 81
- 00440832 001930 Setting tempo to 81
- 00445440 001936 Setting tempo to 81
- 00449536 001940 Setting tempo to 81
- 00454144 001944 Setting tempo to 81
- 00458752 001948 Setting tempo to 81
- 00463360 001952 Setting tempo to 81
- 00467456 001957 Setting tempo to 81
- 00472064 001961 Setting tempo to 81
- 00476672 001966 Setting tempo to 81
- 00481280 001974 Setting tempo to 81
- 00485376 001976 Setting tempo to 81
- 00489984 001981 Setting tempo to 81
- 00494592 001984 Setting tempo to 81
- 00499200 001987 Setting tempo to 81
- 00503296 001990 Setting tempo to 81
- 00507904 001994 Setting tempo to 81
- 00512512 001999 Setting tempo to 81
- 00528896 002015 Reached end of MIDI track
- 00529408 002298 Total processing time 2sec, approximate breakdown:
- 00529408 002299   MrsWatson Initialization: 1sec (64.9%)
- 00529408 002299   MrsWatson Input Source: 14ms (0.6%)
- 00529408 002299   MrsWatson Output Source: 24ms (1.1%)
- 00529408 002299   DSK-TheGrand.vst Audio Processing: 483ms (21.1%)
- 00529408 002299   DSK-TheGrand.vst MIDI Processing: 11ms (0.5%)
- 00529408 002299 Read 250 MIDI events from ../../Little File.mid
- 00529408 002299 Wrote 529408 frames to ./out.wav
- 00529408 002299 Shutting down
- 00529408 002299 Closing plugin 'DSK-TheGrand.vst'
- 00529408 002407 Goodbye!
`

[SampleMIDIinAndWAVout.zip](https://github.com/teragonaudio/MrsWatson/files/1459415/SampleMIDIinAndWAVout.zip)

**Comment by gburlet** [comment]
I'm also seeing that tempo events are ignored. Bump!
