### ISSUE TITLE
Unable to generate Audio using Kontakt 5 Player.

### ISSUE THREAD

**Issue by prateekrajdev** [teragonaudio/MrsWatson#288]
I am facing an issue similar to #281. I am trying to load Kontakt Player along with a fxp file, (as mentioned in the issue thread). I get an audio file which has 0 notes, 0s(1 KB file), as mentioned in the log below, wrote 0 frames to wav file. I also observed that MrsWatson is opening a pop up window which is opened while you try to load the plugin using a host(the loading window, which I assume loads samples).But in case of MrsWatson, it a opened for a much shorter time than it is opened for a DAW(I used FL Studio).

`.\mrswatson64.exe -p '.\Kontakt 5.dll',.\drum5.fxp -m .\hitT0.mid -o out.wav
- 00000000 000000 MrsWatson version 0.9.7 initialized, build 20140125
W 00000000 000000 Running in 64-bit mode, this is experimental. Hold on to your hats!
- 00000000 000000 Opening preset '.\drum5.fxp' for plugin
- 00000000 000000 Plugin '.\Kontakt 5.dll' is of type VST2.x
- 00000000 000000 Opening VST2.x plugin '.\Kontakt 5.dll'
- 00000000 001094 Plugin 'NiO5' asked if host canDo 'receiveVstTimeInfo' (unimplemented)
- 00000000 001094 Plugin 'NiO5' asked if host canDo 'asyncProcessing' (unimplemented)
- 00000000 001094 Plugin 'NiO5' asked if host canDo 'supplyIdle' (unimplemented)
- 00000000 001094 Plugin 'NiO5' asked if host canDo 'supportShell' (unimplemented)
- 00000000 001094 Plugin 'NiO5' asked if host canDo 'editFile' (unimplemented)
- 00000000 001235 Plugin 'NiO5' asked if host canDo 'NIMKPIVendorSpecificCallbacks' (unimplemented)
- 00000000 003188 Loaded preset '<unknown>' in plugin 'Kontakt 5.dll'
- 00000000 003188 Starting processing input source
- 00000000 003188 Setting tempo to 241730874
- 00000000 003188 Setting tempo to 241730874
- 00000000 003188 Setting tempo to 241730874
- 00352768 003219 Reached end of MIDI track
- 00352768 003219 Finished processing input source
- 00353280 003235 Total processing time 3sec, approximate breakdown:
- 00353280 003235   MrsWatson Initialization: 3sec (98.6%)
- 00353280 003235   MrsWatson Input Source: 3ms (0.1%)
- 00353280 003235   MrsWatson Output Source: 0ms (0.0%)
- 00353280 003235   .\Kontakt 5.dll Audio Processing: 22ms (0.7%)
- 00353280 003235   .\Kontakt 5.dll MIDI Processing: 0ms (0.0%)
- 00353280 003235 Read 44 MIDI events from .\hitT0.mid
- 00353280 003235 Wrote 0 frames to out.wav
- 00353280 003235 Shutting down
- 00353280 003235 Closing plugin 'Kontakt 5.dll'
- 00353280 003860 Goodbye!
`
I am also attaching two files.
1) log.txt  (log file generated by --error-report) [log.txt](https://github.com/teragonaudio/MrsWatson/files/3025477/log.txt)
2) out-verbose.log (generated by --verbose)[out-verbose.log] 
 (https://github.com/teragonaudio/MrsWatson/files/3025478/out-verbose.log)

Could there be some trouble with loading the sample package or determining path?

**Comment by williamsharkey** [comment]
Try changing quotations to : 

.\mrswatson64.exe -p “.\Kontakt 5.dll,.\drum5.fxp” -m .\hitT0.mid -o out.wav

Also try removing relative address (I expect it is not necessary as you already have changed directory to the files):

mrswatson64.exe -p “Kontakt 5.dll,drum5.fxp” -m hitT0.mid -o out.wav

**Comment by prateekrajdev** [comment]
I tried the following suggestions. I am still getting 0 frames in the audio file. Also with Kontakt 6,
I am getting the same output as described above.  This one extra line of log that appears with Kontakt 6:
"cannot resolve resource: resources_ENG"  and also the log is a bit different. (difference is in the line after the above stated line 003640).

mrswatson64.exe -p "Kontakt.dll,drum.fxp" -m ./chordsT0.mid -o ./out.wav
- 00000000 000000 MrsWatson version 0.9.7 initialized, build 20140125
W 00000000 000000 Running in 64-bit mode, this is experimental. Hold on to your hats!
- 00000000 000000 Opening preset 'drum.fxp' for plugin
- 00000000 000000 Plugin 'Kontakt.dll' is of type VST2.x
- 00000000 000000 Opening VST2.x plugin 'Kontakt.dll'
- 00000000 001047 Plugin 'Ni$D' asked if host canDo 'receiveVstTimeInfo' (unimplemented)
- 00000000 001047 Plugin 'Ni$D' asked if host canDo 'asyncProcessing' (unimplemented)
- 00000000 001047 Plugin 'Ni$D' asked if host canDo 'supplyIdle' (unimplemented)
- 00000000 001047 Plugin 'Ni$D' asked if host canDo 'supportShell' (unimplemented)
- 00000000 001047 Plugin 'Ni$D' asked if host canDo 'editFile' (unimplemented)
- 00000000 001297 Plugin 'Ni$D' asked if host canDo 'NIMKPIVendorSpecificCallbacks' (unimplemented)
cannot resolve resource: resources_ENG
- 00000000 003640 Loaded preset 'DrumMic'a! V1_0 de' in plugin 'Kontakt.dll'
- 00000000 003640 Starting processing input source
- 00000000 003640 Setting tempo to 241730874
- 00000000 003640 Setting tempo to 241730874
- 00000000 003640 Setting tempo to 241730874
- 00372736 004281 Reached end of MIDI track
- 00372736 004281 Finished processing input source
- 00373248 004297 Total processing time 4sec, approximate breakdown:
- 00373248 004297   MrsWatson Initialization: 3sec (84.6%)
- 00373248 004297   MrsWatson Input Source: 10ms (0.2%)
- 00373248 004297   MrsWatson Output Source: 1ms (0.0%)
- 00373248 004297   Kontakt.dll Audio Processing: 627ms (14.6%)
- 00373248 004312   Kontakt.dll MIDI Processing: 0ms (0.0%)
- 00373248 004312 Read 60 MIDI events from ./chordsT0.mid
- 00373248 004312 Wrote 0 frames to ./out.wav
- 00373248 004312 Shutting down
- 00373248 004312 Closing plugin 'Kontakt.dll'
- 00373248 004812 Goodbye!

**Comment by williamsharkey** [comment]
Try again using a non drum preset, like a keyboard synth or piano. Then try using this midi algoind.com/vapor/nice.mid

**Comment by prateekrajdev** [comment]
I tried using the above configuration and using combinations with the previously suggestion, but I get the same output.

**Comment by williamsharkey** [comment]
How are you creating the .fxp file? I assume a Daw host, and are you using 64 or 32 bit? Pick a free kontact library and choose one of the first synth,piano or keyboard presets, and report which preset you chose using. Upload your .fxp file too. Upload a screenshot of the a bash os or cmd dir of the contents of the folder you are running in.
Thanks, Wm

**Comment by prateekrajdev** [comment]
I am using FL studio using the method that you suggested in #281. I am using 64 bit. So far I have tested three libraries:
1) Drum : https://de-de.sennheiser.com/drummica - used the default preset 
2) Guitar : http://www.pettinhouse.com/html/acousticguitar_free.html - used the default preset
3) Piano :  [http://www.mediafire.com/download/6zd3w39op0tiq2c/MSLP_Piano_Grand_Soft.nki](url) 
used the default preset

The screenshot is attached 
![kontakt-dir-list](https://user-images.githubusercontent.com/9334835/55397629-45580e00-5564-11e9-92e8-ff65667a19f2.jpg)

Link to fxps:
https://drive.google.com/open?id=10K2Cch2yVu1pi4qaQeIJXJPExMmz-9Ru 

Could you specify which OS and library are you using and also the directory structure(which file is supposed to be kept where?) that makes it work?

**Comment by williamsharkey** [comment]
The latest released version of mrswatson is 9.8 . In the output above, it looks like you are running 9.7 .

9.8 seems to have about an extra year of bug fixes included over 9.7, so it's worth trying the new version and letting us know if there are any improvements.

**Comment by prateekrajdev** [comment]
Yes. It worked. Thanks a lot. I should have figured this out.
