### ISSUE TITLE
Add option for setting bitrate

### ISSUE THREAD

**Issue by nikreiman** [teragonaudio/MrsWatson#39]
Right now the bitrate is hardcoded to 16, which applies for both PCM data (reading & writing), and AIFF data (writing). Would be nice to have an option to set this to higher rates if desired.

**Comment by nikreiman** [comment]
Closing issue, this is now supported with the `--bit-depth` switch. However, this option is only necessary if you are loading raw PCM files; if you use any other format (ie, AIFF/WAVE/FLAC), MrsWatson will automatically detect the bit depth and use it for processing.

Please note that like the channel rate and sample count, the bit depth used by MrsWatson applies to both input and output sources. So another tool such as ffmpeg should be used if the output file must be converted to another bitrate.

ping @BasicPro, let me know if you want to try a beta build.

**Comment by BasicPro** [comment]
I'm having some issues with 32 bit files, the output I get is just a noise "plop". 24bit seems to work fine.

Regards
